"""descripcion

Revision ID: f9c3f511fa0d
Revises: 0d333f9b4f3f
Create Date: 2025-10-18 14:26:12.778167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c3f511fa0d'
down_revision: Union[str, Sequence[str], None] = '0d333f9b4f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pokemon_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pokemon_ids')
    # ### end Alembic commands ###
